export interface ListWarga {
    id: string;
    // idType?: string;
    nik: string;
    nama: string;
    email: string;
    namaRT: string;
    nomorKK: string;
    isKK: string;
    familyGroup: string;
    // asalKTP?: string;
    // jenisKelamin: number;
    // tempatLahir: string;
    // agama: number;
    // pendidikan: number;
    // jenisPekerjaan: number;
    // statusPerkawinan: number;
    // hubunganKeluarga: number;
    // kewarganegaraan: number;
    alamatTinggal: string;
    // alamatKTP: string;
    // statusWarga: number;
    // keterangan?: string;
    // noHP?: string;
    // golDarah?: number;
    // pernahCovid?: number;
    // vaksinCovidKe1?: string;
    // vaksinCovidKe2?: string;
    // vaksinCovidKe3?: string;
}
